### ISSUE TITLE
Renderer::render() seems to not display anything for unknown reason

### ISSUE THREAD

**Issue by super-continent** [Veykril/imgui-dx9-renderer#4]
I was writing a DX9 EndScene hook that can work for applications to display graphics over another processes window, [found here](https://github.com/super-continent/rust-imgui-dx9-hook), and I seem to have everything set up for it to theoretically be able to render an imgui overlay, but it seems to not work at all, I've inspected it myself and tried to write my own port of the [imgui_impl_win32.cpp](https://github.com/super-continent/imgui-impl-win32-rs) (which is not yet finished, though it should set up what state is necessary for the program to work.) and it still seems to render nothing, despite returning no errors.

If you have any insight on whats wrong with either my code, or why the library isn't displaying anything, that would be very helpful.

**Comment by Veykril** [comment]
From a rough glance I don't really see anything that's missing but I also don't have the time to look more into it atm. You can check out this project which uses this renderer(version 0.4.0 though) and try to see what they do https://github.com/Crauzer/sidonia/blob/master/src/core/ui.rs.

**Comment by super-continent** [comment]
Ah, thank you for the resource, I wasn't able to find any crates doing this myself. If this functions that means it must be an issue with my code and not the renderer. I'll take a look and see what they do differently.
